# Generated by Django 4.2.5 on 2023-09-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Producto',
        ),
    ]
